# Generated by Django 5.0.12 on 2025-03-05 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_userlocation_current_zone_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('particle', 'Particle System'), ('rigid_body', 'Rigid Body Dynamics'), ('fluid', 'Fluid Dynamics'), ('cloth', 'Cloth Simulation'), ('soft_body', 'Soft Body Dynamics'), ('gravity', 'Gravitational Simulation'), ('electromagnetic', 'Electromagnetic Simulation'), ('custom', 'Custom Physics')], max_length=20)),
                ('entities', models.JSONField(default=dict, help_text='Objects with physics properties')),
                ('forces', models.JSONField(default=dict)),
                ('constraints', models.JSONField(default=dict)),
                ('iteration_rate', models.FloatField(default=60.0, help_text='Iterations per second')),
                ('visual_effects', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicsInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_data', models.JSONField(default=dict)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('objectives_achieved', models.JSONField(blank=True, default=list)),
                ('session_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physics_interactions', to='core.playerprofile')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='physics.physicssimulation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
