# Generated by Django 5.0.12 on 2025-03-01 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# [REF:00a1b2c3-d4e5-f6a7-b8c9-d0e1f2a3b4c5:CORE_USER_SYSTEM]
# [CLAUDE:CHECK_PATTERN:experience_progression]
# [CLAUDE:OPTIMIZATION_LAYER:START]
# This file is part of the core_user_system component
# See .claude/README.md for more information
# [CLAUDE:OPTIMIZATION_LAYER:END]


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerprofile_avatar_playerprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='market_items/')),
                ('economic_layer', models.CharField(choices=[('outer', 'Port City (Outer Layer)'), ('middle', 'Laws Model (Middle Layer)'), ('inner', 'Republic Model (Inner Layer)')], default='outer', max_length=10)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_type', models.CharField(choices=[('credits', 'Credits'), ('merit', 'Merit-Based'), ('contribution', 'Contribution-Based')], default='credits', max_length=50)),
                ('category', models.CharField(choices=[('physical', 'Physical Goods'), ('service', 'Services'), ('digital', 'Digital Assets'), ('investment', 'Investments'), ('skill', 'Skills & Knowledge'), ('experience', 'Experiences'), ('collaboration', 'Collaborative Opportunities'), ('resource', 'Resource Sharing')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('min_rank_required', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('recommendation_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_users', to='core.marketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
