# Generated by Django 5.0.12 on 2025-02-27 18:57

from django.db import migrations, models

# [REF:22c3d4e5-f6a7-b8c9-d0e1-f2a3b4c5d6e7:EXPERIENCE_SYSTEM]
# [CLAUDE:CHECK_PATTERN:experience_progression]
# [CLAUDE:OPTIMIZATION_LAYER:START]
# This file is part of the experience_system component
# See .claude/README.md for more information
# [CLAUDE:OPTIMIZATION_LAYER:END]


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geographic latitude for displaying on the map', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geographic longitude for displaying on the map', null=True),
        ),
    ]
